server:
  port: 8888

logging:
  level:
    root: info

spring:
  application:
    name: kanban
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/kanban-db

telegram:
  bot:
    name: asteises_kanban_bot
    token: 6665594388:AAHlHqjsr-CJpJT9gdg7D9KCJwlYX-j9Z6M